### ISSUE TITLE
bug with new version phpcs 2.3.4

### ISSUE THREAD

**Issue by evilebottnawi** [JustBlackBird/gulp-phpcs#15] opened 2015-09-10 11:18 UTC
if not use ```javascript 
stream.resume();
```
in code:
```javascript
var stream = gulp.src(directory, {
                    cwd: process.cwd()
                })
                    .pipe($.plumber(options.build.plumber))
                    .pipe($.phpcs({
                        bin: phpcsPath,
                        standard: standard,
                        encoding: 'utf-8',
                        colors: true
                    }))
                    .pipe($.phpcs.reporter('log'));

stream.resume();
stream.on('end', done);
```
then stream silent stop.

**Comment by JustBlackBird** [comment] 2015-09-11 17:34
I have a few questions about the problem:
  1. Does `gulp-phpcs` work for you with an older version of PHPCS?
  2. Does PHPCS work from terminal (without `gulp-phpcs`)?
  3. Could you please provide the whole gulp task where `gulp-phpcs` is used?

**Comment by evilebottnawi** [comment] 2015-09-14 08:46
1. Yes
2. Yes
3. above

**Comment by JustBlackBird** [comment] 2015-09-16 12:07
First of all, there is no PHPCS v2.4.3. As I see, the latest version is [**2.3.4**](https://packagist.org/packages/squizlabs/php_codesniffer#2.3.4).

Next, you did not list the _minimal_ test case that illustrates the problem. In your code above there are too many undefined variables (`directory`, `options`, `standard` and so on). So, I've created a test case to trace the problem. Here is the code:

```js
var gulp = require('gulp'),
    phpcs = require('gulp-phpcs');

gulp.task('default', function() {
    return gulp.src(['./test/*.php'])
        .pipe(phpcs({
            bin: './vendor/bin/phpcs',
            standard: 'PSR2',
            encoding: 'utf-8',
            colors: true
        }))
        .pipe(phpcs.reporter('log'));
});
```

This test case works fine with PHPCS 2.3.4, so I think the problem is outside `gulp-phpcs` plugin.

**Comment by evilebottnawi** [comment] 2015-09-16 13:22
@JustBlackBird In the near future I will test again and tell here

**Comment by JustBlackBird** [comment] 2015-10-02 10:57
For now I'm closing the issue. If the problem persists and you will be able to provide more details about it it I'll reopen the issue.

**Closed by JustBlackBird** 2015-10-02 10:57 UTC
Labels: invalid
